/**
 * 全 SE の設計値（Tone.js オフライン生成の入力）。
 * ゲーム本体からは import しない。
 */

export type SfxCategory = 'combat' | 'ui' | 'event' | 'element'

export type SfxPreset = {
  /** 出力ファイル名（拡張子なし）。GameAudioSystem のパスと一致 */
  id: string
  /** 人間向けの用途説明 */
  purpose: string
  category: SfxCategory
  /** パッチ関数のキー（schedule 側と対応） */
  patch: string
  /** Offline レンダー秒数（余裕を含む） */
  renderSeconds: number
  /** 目標の鳴り終わり秒数（ざっくり） */
  durationTarget: number
  /** 検査用の下限・上限秒 */
  durationMin: number
  durationMax: number
  gain: number
  attack: number
  release: number
  pitchHz: number
  filterHz: number
  filterQ: number
  noiseAmount: number
  resonance: number
  distortion: number
  variation: number
  blurb: string
}

/** BGM は絶対に触らない */
export const PROTECTED_BGM_FILES = [
  'title_bgm.ogg',
  'plains_bgm.ogg',
  'forest_bgm.ogg',
  'volcano_bgm.ogg',
  'ruins_bgm.ogg',
  'area_clear_bgm.ogg',
] as const

/**
 * カテゴリ別の秒数上限（検査用）。
 * combat: 0.2 / ui: 0.3 / event は個別 durationMax
 */
export const CATEGORY_HARD_MAX: Record<SfxCategory, number | null> = {
  combat: 0.2,
  ui: 0.3,
  event: null,
  element: 0.2,
}

export const SFX_PRESETS: SfxPreset[] = [
  // --- 属性: Power ---
  {
    id: 'player_fire_power',
    purpose: 'パワー弾の発射',
    category: 'element',
    patch: 'power_fire',
    renderSeconds: 0.14,
    durationTarget: 0.08,
    durationMin: 0.06,
    durationMax: 0.09,
    gain: 0.55,
    attack: 0.004,
    release: 0.02,
    pitchHz: 880,
    filterHz: 3200,
    filterQ: 0.7,
    noiseAmount: 0.08,
    resonance: 0.2,
    distortion: 0,
    variation: 0.05,
    blurb: 'FM/短い周波数下降のクリーンな魔法弾。ノイズ最少',
  },
  {
    id: 'player_hit_power',
    purpose: 'パワー弾の命中',
    category: 'element',
    patch: 'power_hit',
    renderSeconds: 0.12,
    durationTarget: 0.065,
    durationMin: 0.05,
    durationMax: 0.08,
    gain: 0.6,
    attack: 0.001,
    release: 0.02,
    pitchHz: 784,
    filterHz: 4200,
    filterQ: 0.7,
    noiseAmount: 0.14,
    resonance: 0.25,
    distortion: 0,
    variation: 0.05,
    blurb: '短いクリーン命中。ピッチ下降のみで明瞭',
  },
  // --- Wind ---
  {
    id: 'player_fire_wind',
    purpose: '風弾の発射',
    category: 'element',
    patch: 'wind_fire',
    renderSeconds: 0.14,
    durationTarget: 0.08,
    durationMin: 0.06,
    durationMax: 0.09,
    gain: 0.85,
    attack: 0.01,
    release: 0.015,
    pitchHz: 1500,
    filterHz: 2800,
    filterQ: 1.4,
    noiseAmount: 0.9,
    resonance: 0.1,
    distortion: 0,
    variation: 0.2,
    blurb: '帯域ノイズ主体の「シュッ」。丸い音程を避ける',
  },
  {
    id: 'player_hit_wind',
    purpose: '風弾の命中',
    category: 'element',
    patch: 'wind_hit',
    renderSeconds: 0.12,
    durationTarget: 0.06,
    durationMin: 0.05,
    durationMax: 0.08,
    gain: 0.9,
    attack: 0.001,
    release: 0.015,
    pitchHz: 1500,
    filterHz: 3400,
    filterQ: 2.2,
    noiseAmount: 0.95,
    resonance: 0.1,
    distortion: 0,
    variation: 0.15,
    blurb: '短い空気切れ。High/BandPass で抜ける',
  },
  // --- Water ---
  {
    id: 'player_fire_water',
    purpose: '水弾の発射',
    category: 'element',
    patch: 'water_fire',
    renderSeconds: 0.15,
    durationTarget: 0.09,
    durationMin: 0.07,
    durationMax: 0.1,
    gain: 0.55,
    attack: 0.006,
    release: 0.02,
    pitchHz: 920,
    filterHz: 2200,
    filterQ: 0.8,
    noiseAmount: 0.07,
    resonance: 0.7,
    distortion: 0,
    variation: 0.1,
    blurb: '近い周波数の液体共鳴 + LowPass。ベル禁止',
  },
  {
    id: 'player_hit_water',
    purpose: '水弾の命中',
    category: 'element',
    patch: 'water_hit',
    renderSeconds: 0.13,
    durationTarget: 0.07,
    durationMin: 0.05,
    durationMax: 0.09,
    gain: 0.65,
    attack: 0.001,
    release: 0.02,
    pitchHz: 920,
    filterHz: 2200,
    filterQ: 0.8,
    noiseAmount: 0.12,
    resonance: 0.75,
    distortion: 0,
    variation: 0.1,
    blurb: '小さな水滴の衝突。わずかなピッチ下降',
  },
  // --- Fire ---
  {
    id: 'player_fire_fire',
    purpose: '火弾の発射',
    category: 'element',
    patch: 'fire_fire',
    renderSeconds: 0.15,
    durationTarget: 0.09,
    durationMin: 0.07,
    durationMax: 0.1,
    gain: 0.7,
    attack: 0.01,
    release: 0.02,
    pitchHz: 520,
    filterHz: 900,
    filterQ: 0.9,
    noiseAmount: 0.85,
    resonance: 0.3,
    distortion: 0.15,
    variation: 0.35,
    blurb: '色付きノイズ + 火の粉。爆発音・重低音なし',
  },
  {
    id: 'player_hit_fire',
    purpose: '火弾の命中',
    category: 'element',
    patch: 'fire_hit',
    renderSeconds: 0.14,
    durationTarget: 0.08,
    durationMin: 0.06,
    durationMax: 0.1,
    gain: 0.75,
    attack: 0.002,
    release: 0.02,
    pitchHz: 460,
    filterHz: 1000,
    filterQ: 1.0,
    noiseAmount: 0.9,
    resonance: 0.3,
    distortion: 0.2,
    variation: 0.4,
    blurb: '短い火花ヒット。長い燃焼はしない',
  },
  // --- Earth ---
  {
    id: 'player_fire_earth',
    purpose: '土弾の発射',
    category: 'element',
    patch: 'earth_fire',
    renderSeconds: 0.15,
    durationTarget: 0.09,
    durationMin: 0.07,
    durationMax: 0.1,
    gain: 0.65,
    attack: 0.006,
    release: 0.02,
    pitchHz: 392,
    filterHz: 780,
    filterQ: 1.0,
    noiseAmount: 0.7,
    resonance: 0.55,
    distortion: 0.05,
    variation: 0.25,
    blurb: '砂粒・軽い石。地震ではなくコッ／ポスッ',
  },
  {
    id: 'player_hit_earth',
    purpose: '土弾の命中',
    category: 'element',
    patch: 'earth_hit',
    renderSeconds: 0.16,
    durationTarget: 0.1,
    durationMin: 0.08,
    durationMax: 0.12,
    gain: 0.7,
    attack: 0.001,
    release: 0.02,
    pitchHz: 330,
    filterHz: 700,
    filterQ: 1.1,
    noiseAmount: 0.75,
    resonance: 0.6,
    distortion: 0.08,
    variation: 0.3,
    blurb: '粒状ノイズ + 短い石の共鳴',
  },
  // player_fire = power のエイリアス（生成後コピー）
  {
    id: 'player_fire',
    purpose: 'デフォルト発射（パワーと同音）',
    category: 'element',
    patch: 'copy_player_fire_power',
    renderSeconds: 0.14,
    durationTarget: 0.08,
    durationMin: 0.06,
    durationMax: 0.09,
    gain: 0.55,
    attack: 0.004,
    release: 0.02,
    pitchHz: 880,
    filterHz: 3200,
    filterQ: 0.7,
    noiseAmount: 0.08,
    resonance: 0.2,
    distortion: 0,
    variation: 0.05,
    blurb: 'player_fire_power と同一ファイル',
  },
  // --- 戦闘 ---
  {
    id: 'enemy_defeat',
    purpose: '敵撃破',
    category: 'event',
    patch: 'enemy_defeat',
    renderSeconds: 0.3,
    durationTarget: 0.18,
    durationMin: 0.13,
    durationMax: 0.24,
    gain: 0.58,
    attack: 0.001,
    release: 0.035,
    pitchHz: 520,
    filterHz: 2100,
    filterQ: 0.85,
    noiseAmount: 0.48,
    resonance: 0.25,
    distortion: 0,
    variation: 0.35,
    blurb: '軽い破裂＋下降。ポッ／シュパッ。大爆発・金属なし',
  },
  {
    id: 'enemy_hit',
    purpose: '敵への軽い命中',
    category: 'combat',
    patch: 'enemy_hit',
    renderSeconds: 0.1,
    durationTarget: 0.055,
    durationMin: 0.04,
    durationMax: 0.07,
    gain: 0.5,
    attack: 0.001,
    release: 0.015,
    pitchHz: 600,
    filterHz: 2400,
    filterQ: 0.7,
    noiseAmount: 0.25,
    resonance: 0.15,
    distortion: 0,
    variation: 0.1,
    blurb: '乾いた軽いヒット',
  },
  {
    id: 'enemy_blocked',
    purpose: '敵の防御／弾き',
    category: 'combat',
    patch: 'enemy_blocked',
    renderSeconds: 0.15,
    durationTarget: 0.09,
    durationMin: 0.07,
    durationMax: 0.11,
    gain: 0.55,
    attack: 0.001,
    release: 0.03,
    pitchHz: 880,
    filterHz: 3200,
    filterQ: 1.2,
    noiseAmount: 0.2,
    resonance: 0.4,
    distortion: 0.05,
    variation: 0.1,
    blurb: '硬い反射。金属ベルではない',
  },
  {
    id: 'coin_pickup',
    purpose: 'コイン取得',
    category: 'combat',
    patch: 'coin_pickup',
    renderSeconds: 0.14,
    durationTarget: 0.08,
    durationMin: 0.06,
    durationMax: 0.1,
    gain: 0.45,
    attack: 0.002,
    release: 0.03,
    pitchHz: 988,
    filterHz: 4000,
    filterQ: 0.6,
    noiseAmount: 0.05,
    resonance: 0.35,
    distortion: 0,
    variation: 0.08,
    blurb: '控えめな上昇ピップ',
  },
  {
    id: 'player_hurt',
    purpose: 'プレイヤー被弾',
    category: 'combat',
    patch: 'player_hurt',
    renderSeconds: 0.2,
    durationTarget: 0.13,
    durationMin: 0.1,
    durationMax: 0.16,
    gain: 0.55,
    attack: 0.003,
    release: 0.04,
    pitchHz: 220,
    filterHz: 1200,
    filterQ: 0.7,
    noiseAmount: 0.3,
    resonance: 0.2,
    distortion: 0.1,
    variation: 0.12,
    blurb: '短い被弾。重すぎず警告音すぎない',
  },
  // --- UI ---
  {
    id: 'menu_move',
    purpose: 'メニュー移動',
    category: 'ui',
    patch: 'menu_move',
    renderSeconds: 0.1,
    durationTarget: 0.055,
    durationMin: 0.04,
    durationMax: 0.07,
    gain: 0.35,
    attack: 0.001,
    release: 0.02,
    pitchHz: 1200,
    filterHz: 5000,
    filterQ: 0.5,
    noiseAmount: 0.1,
    resonance: 0.1,
    distortion: 0,
    variation: 0.05,
    blurb: '小さいクリック',
  },
  {
    id: 'menu_cancel',
    purpose: 'メニューキャンセル',
    category: 'ui',
    patch: 'menu_cancel',
    renderSeconds: 0.15,
    durationTarget: 0.09,
    durationMin: 0.07,
    durationMax: 0.12,
    gain: 0.4,
    attack: 0.002,
    release: 0.03,
    pitchHz: 480,
    filterHz: 2800,
    filterQ: 0.6,
    noiseAmount: 0.08,
    resonance: 0.15,
    distortion: 0,
    variation: 0.05,
    blurb: '少し低い戻る音',
  },
  {
    id: 'shop_purchase',
    purpose: 'ショップ購入',
    category: 'ui',
    patch: 'shop_purchase',
    renderSeconds: 0.3,
    durationTarget: 0.2,
    durationMin: 0.16,
    durationMax: 0.24,
    gain: 0.45,
    attack: 0.004,
    release: 0.05,
    pitchHz: 660,
    filterHz: 3500,
    filterQ: 0.6,
    noiseAmount: 0.05,
    resonance: 0.3,
    distortion: 0,
    variation: 0.1,
    blurb: '短い肯定音（2音上昇）',
  },
  // --- イベント ---
  {
    id: 'level_up',
    purpose: 'レベルアップ',
    category: 'event',
    patch: 'level_up',
    renderSeconds: 0.75,
    durationTarget: 0.55,
    durationMin: 0.45,
    durationMax: 0.65,
    gain: 0.5,
    attack: 0.01,
    release: 0.08,
    pitchHz: 523,
    filterHz: 4500,
    filterQ: 0.5,
    noiseAmount: 0.04,
    resonance: 0.25,
    distortion: 0,
    variation: 0.05,
    blurb: 'C→E→G の協和上昇。悲しい下降禁止',
  },
  {
    id: 'stage_clear',
    purpose: 'ステージクリア',
    category: 'event',
    patch: 'stage_clear',
    renderSeconds: 1.5,
    durationTarget: 1.1,
    durationMin: 0.9,
    durationMax: 1.3,
    gain: 0.5,
    attack: 0.015,
    release: 0.12,
    pitchHz: 392,
    filterHz: 4000,
    filterQ: 0.5,
    noiseAmount: 0.03,
    resonance: 0.2,
    distortion: 0,
    variation: 0.05,
    blurb: '短い勝利感',
  },
  {
    id: 'area_clear',
    purpose: 'エリアクリア',
    category: 'event',
    patch: 'area_clear',
    renderSeconds: 2.0,
    durationTarget: 1.5,
    durationMin: 1.2,
    durationMax: 1.8,
    gain: 0.52,
    attack: 0.02,
    release: 0.15,
    pitchHz: 392,
    filterHz: 4200,
    filterQ: 0.5,
    noiseAmount: 0.03,
    resonance: 0.25,
    distortion: 0,
    variation: 0.05,
    blurb: 'Stage Clear より一段豪華',
  },
  {
    id: 'game_over',
    purpose: 'ゲームオーバー',
    category: 'event',
    patch: 'game_over',
    renderSeconds: 1.3,
    durationTarget: 0.9,
    durationMin: 0.7,
    durationMax: 1.1,
    gain: 0.48,
    attack: 0.02,
    release: 0.15,
    pitchHz: 330,
    filterHz: 2200,
    filterQ: 0.6,
    noiseAmount: 0.06,
    resonance: 0.2,
    distortion: 0,
    variation: 0.05,
    blurb: '短い下降感。過度に暗くしない',
  },
  // --- Orbiting Orb（氷）---
  {
    id: 'orbiting_orb_obtain',
    purpose: 'Orbiting Orb 取得・展開',
    category: 'event',
    patch: 'ice_obtain',
    renderSeconds: 0.42,
    durationTarget: 0.28,
    durationMin: 0.18,
    durationMax: 0.38,
    gain: 0.42,
    attack: 0.008,
    release: 0.06,
    pitchHz: 740,
    filterHz: 3600,
    filterQ: 0.9,
    noiseAmount: 0.22,
    resonance: 0.55,
    distortion: 0,
    variation: 0.04,
    blurb: '氷晶が広がる冷気シマー。水滴・泡にしない',
  },
  {
    id: 'orbiting_orb_hit',
    purpose: 'Orbiting Orb 敵命中',
    category: 'combat',
    patch: 'ice_hit',
    renderSeconds: 0.14,
    durationTarget: 0.07,
    durationMin: 0.05,
    durationMax: 0.1,
    gain: 0.38,
    attack: 0.001,
    release: 0.015,
    pitchHz: 980,
    filterHz: 4200,
    filterQ: 1.0,
    noiseAmount: 0.28,
    resonance: 0.4,
    distortion: 0,
    variation: 0.04,
    blurb: '小さな氷片が軽く砕ける。高頻度でも疲れない',
  },
  {
    id: 'orbiting_orb_shatter',
    purpose: 'Orbiting Orb が敵弾を消滅',
    category: 'combat',
    patch: 'ice_shatter',
    renderSeconds: 0.14,
    durationTarget: 0.065,
    durationMin: 0.045,
    durationMax: 0.09,
    gain: 0.34,
    attack: 0.002,
    release: 0.02,
    pitchHz: 1200,
    filterHz: 3800,
    filterQ: 0.85,
    noiseAmount: 0.7,
    resonance: 0.35,
    distortion: 0,
    variation: 0.04,
    blurb: '冷気でシュッと消える迎撃音。派手にしない',
  },
]

export const PRESET_BY_ID: Record<string, SfxPreset> = Object.fromEntries(
  SFX_PRESETS.map((p) => [p.id, p]),
)
