import { GAME_HEIGHT, GAME_WIDTH } from './layout'

/** タイトル下部の丸ボタン（左Support／右BGM）で共有する見た目と配置。 */
export const BOTTOM_CORNER_BUTTON_EDGE_OFFSET = 30
export const BOTTOM_CORNER_BUTTON_CENTER_Y =
  GAME_HEIGHT - BOTTOM_CORNER_BUTTON_EDGE_OFFSET
export const BOTTOM_CORNER_BUTTON_RADIUS = 19
export const BOTTOM_CORNER_BUTTON_STROKE_WIDTH = 2
export const BOTTOM_CORNER_BUTTON_ICON_COLOR = 0xd4d4d8
export const BOTTOM_CORNER_BUTTON_ICON_CSS_COLOR = '#d4d4d8'
export const BOTTOM_CORNER_BUTTON_SELECTED_COLOR = 0xfde68a
export const BOTTOM_CORNER_BUTTON_DEPTH = 520
export const BOTTOM_CORNER_BUTTON_LABEL_OFFSET_Y = 30
export const BOTTOM_CORNER_BUTTON_LABEL_FONT_SIZE = '11px'

export const TITLE_SUPPORT_BUTTON_CENTER_X = BOTTOM_CORNER_BUTTON_EDGE_OFFSET
export const BGM_TOGGLE_BUTTON_CENTER_X =
  GAME_WIDTH - BOTTOM_CORNER_BUTTON_EDGE_OFFSET
