#!/usr/bin/env node
/**
 * docs/audio/sfx-external-import.json の Combat Core 3 Entry から
 * Catalog 用の外部候補定数ファイルを生成する。
 *
 * 使い方:
 *   node tools/sfx_catalog/generate_combat_core_external_candidates.mjs
 *
 * Runtime では Manifest を fetch しない。生成結果の TS だけをバンドルする。
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const rootDir = path.resolve(__dirname, '../..')
const manifestPath = path.join(rootDir, 'docs/audio/sfx-external-import.json')
const outPath = path.join(
  rootDir,
  'src/games/survivor/constants/combatCoreExternalCandidates.ts',
)

const ENTRY_SPECS = [
  {
    entryId: 'skill.power.cast',
    exportName: 'COMBAT_CORE_EXTERNAL_CAST',
    labelPrefix: 'Cast',
  },
  {
    entryId: 'skill.power.impact',
    exportName: 'COMBAT_CORE_EXTERNAL_IMPACT',
    labelPrefix: 'Impact',
  },
  {
    entryId: 'enemy.defeat',
    exportName: 'COMBAT_CORE_EXTERNAL_DEFEAT',
    labelPrefix: 'Defeat',
  },
]

function localPathToCatalogPath(localPath) {
  if (localPath.startsWith('public/')) {
    return localPath.slice('public/'.length)
  }
  return localPath
}

function titleFromLocalPath(localPath) {
  const base = path.basename(localPath).replace(/\.(ogg|wav|mp3|flac)$/i, '')
  let name = base.replace(/^(opengameart_|kenney_)/i, '')
  name = name.replace(/-\d+$/, '')
  const words = name.split(/[-_]+/).filter((w) => w.length > 0)
  return words
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join(' ')
}

function buildLabel(labelPrefix, rank, localPath) {
  const rankText = String(rank).padStart(2, '0')
  const title = titleFromLocalPath(localPath)
  return `${labelPrefix} ${rankText} — ${title}`
}

function escapeTsString(value) {
  return JSON.stringify(value)
}

function variantToTs(candidate, labelPrefix) {
  const catalogPath = localPathToCatalogPath(candidate.localPath)
  const label = buildLabel(labelPrefix, candidate.recommendationRank, candidate.localPath)
  const entryFolder = candidate.entryId.split('.').join('-')
  const numberText = String(candidate.recommendationRank).padStart(2, '0')
  const durationMs = Math.round(candidate.durationMs)
  const lines = [
    '  {',
    `    id: ${escapeTsString(candidate.candidateId)},`,
    `    label: ${escapeTsString(label)},`,
    `    path: ${escapeTsString(catalogPath)},`,
    `    audioKey: ${escapeTsString(`sfx-catalog-${entryFolder}-external-${numberText}`)},`,
    `    status: 'candidate',`,
    `    origin: 'external-free',`,
    `    sourceName: ${escapeTsString(candidate.sourceName)},`,
    `    sourcePageUrl: ${escapeTsString(candidate.sourcePageUrl)},`,
    `    downloadUrl: ${escapeTsString(candidate.downloadUrl)},`,
    `    author: ${escapeTsString(candidate.author)},`,
    `    licenseName: ${escapeTsString(candidate.licenseName)},`,
    `    licenseUrl: ${escapeTsString(candidate.licenseUrl)},`,
    `    attributionRequired: ${candidate.attributionRequired ? 'true' : 'false'},`,
    `    attributionText: ${escapeTsString(candidate.attributionText ?? '')},`,
    `    downloadedAt: ${escapeTsString(candidate.downloadedAt)},`,
    `    originalFilename: ${escapeTsString(candidate.originalFilename)},`,
    `    modifiedFromOriginal: ${candidate.modifiedFromOriginal ? 'true' : 'false'},`,
    `    modificationNotes: ${escapeTsString(candidate.modificationNotes)},`,
    `    checksumSha256: ${escapeTsString(candidate.checksumSha256)},`,
    `    durationMs: ${durationMs},`,
    `    sampleRate: ${candidate.sampleRate},`,
    `    channels: ${candidate.channels},`,
    `    format: ${escapeTsString(candidate.format)},`,
    `    soundFeatures: ${escapeTsString(candidate.soundFeatures)},`,
    `    source: ${escapeTsString(candidate.sourceName)},`,
    `    license: 'CC0-1.0',`,
    '  },',
  ]
  return lines.join('\n')
}

function recommendationToTs(candidate) {
  const features = String(candidate.soundFeatures || '')
    .split(',')
    .map((part) => part.trim())
    .filter((part) => part.length > 0)
  const directionTs = features.map((f) => escapeTsString(f)).join(', ')
  return [
    '  {',
    `    variantId: ${escapeTsString(candidate.candidateId)},`,
    `    rank: ${candidate.recommendationRank},`,
    `    direction: [${directionTs}],`,
    `    reason: ${escapeTsString(candidate.recommendationReason)},`,
    '  },',
  ].join('\n')
}

function main() {
  const raw = fs.readFileSync(manifestPath, 'utf8')
  const manifest = JSON.parse(raw)
  const chunks = []
  chunks.push('// AUTO-GENERATED by tools/sfx_catalog/generate_combat_core_external_candidates.mjs')
  chunks.push('// Source: docs/audio/sfx-external-import.json (Combat Core external candidates)')
  chunks.push('// Do not edit by hand. Re-run the generator after Manifest updates.')
  chunks.push("import type { SfxCatalogRecommendation, SfxCatalogVariant } from './sfxCatalog'")
  chunks.push('')

  for (const spec of ENTRY_SPECS) {
    const entry = manifest.entries[spec.entryId]
    if (entry === undefined || !Array.isArray(entry.candidates)) {
      throw new Error(`Missing candidates for ${spec.entryId}`)
    }
    const sorted = entry.candidates.slice().sort((a, b) => {
      return a.recommendationRank - b.recommendationRank
    })
    if (sorted.length !== 15) {
      throw new Error(`${spec.entryId} expected 15 candidates, got ${sorted.length}`)
    }
    for (let index = 0; index < sorted.length; index++) {
      const candidate = sorted[index]
      const expectedId = `${spec.entryId}-external-${String(index + 1).padStart(2, '0')}`
      if (candidate.candidateId !== expectedId) {
        throw new Error(
          `${spec.entryId} candidateId mismatch at rank ${candidate.recommendationRank}: ${candidate.candidateId}`,
        )
      }
      const expectedPath = candidate.localPath
      if (!fs.existsSync(path.join(rootDir, expectedPath))) {
        throw new Error(`Missing file: ${expectedPath}`)
      }
    }

    chunks.push(`/** Manifest external candidates for ${spec.entryId} (rank order). */`)
    chunks.push(
      `export const ${spec.exportName}_VARIANTS: SfxCatalogVariant[] = [`,
    )
    for (const candidate of sorted) {
      chunks.push(variantToTs(candidate, spec.labelPrefix))
    }
    chunks.push(']')
    chunks.push('')

    const top3 = sorted.filter((c) => c.recommendationRank >= 1 && c.recommendationRank <= 3)
    chunks.push(
      `export const ${spec.exportName}_RECOMMENDATIONS: SfxCatalogRecommendation[] = [`,
    )
    for (const candidate of top3) {
      chunks.push(recommendationToTs(candidate))
    }
    chunks.push(']')
    chunks.push('')
  }

  chunks.push('export const COMBAT_CORE_EXTERNAL_ENTRY_IDS = [')
  for (const spec of ENTRY_SPECS) {
    chunks.push(`  ${escapeTsString(spec.entryId)},`)
  }
  chunks.push('] as const')
  chunks.push('')

  fs.writeFileSync(outPath, chunks.join('\n') + '\n', 'utf8')
  console.log(`Wrote ${path.relative(rootDir, outPath)}`)
}

main()
